param([switch]$SkipBuild)
$ErrorActionPreference='Stop'
$root=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
$engine=& (Join-Path $PSScriptRoot 'Find-Engine.ps1')
if(!$SkipBuild){
    & (Join-Path $PSScriptRoot 'Build-Star.ps1') -Target Game -EngineRoot $engine -NoUba
    if($LASTEXITCODE -ne 0){throw 'Game build failed'}
    # Remove only disposable PCH files generated by this independent build.
    $cache=Join-Path $root 'Intermediate/Build/Win64/x64/Star'
    if(Test-Path -LiteralPath $cache){
        foreach($item in (Get-ChildItem -LiteralPath $cache -Recurse -File -Filter '*.pch')){
            if(!$item.FullName.StartsWith($root+'\Intermediate\')){throw 'Unexpected build cache target'}
            Remove-Item -LiteralPath $item.FullName
        }
    }
}
$log=Join-Path $root ('work/logs/solar-package-'+[DateTime]::UtcNow.ToString('yyyyMMdd-HHmmss')+'.log')
& (Join-Path $engine 'Engine/Build/BatchFiles/RunUAT.bat') BuildCookRun "-project=$root/Star.uproject" -noP4 -unattended -platform=Win64 -clientconfig=Development -skipbuild -nocompileeditor -cook -iterate -stage -pak -iostore -compressed -nodebuginfo 2>&1 | Tee-Object -FilePath $log
if($LASTEXITCODE -ne 0){throw "Cook/stage failed: $log"}
if(!(Test-Path "$root/Saved/StagedBuilds/Windows/Star.exe")){throw 'Missing staged executable'}
Write-Output 'Solar Windows package staged successfully'
