"""Create a 10m Apollo17 far tier without changing any existing 5m samples."""
from pathlib import Path
import sys,json,hashlib,time
sys.path.insert(0,str(Path('work/lunar-panorama/python').resolve()))
import numpy as np,tifffile
from scipy.ndimage import distance_transform_edt
root=Path('.');src=Path('./work/trees/data/work/raw/NAC_DTM_APOLLO17.TIF');out=root/'Content/Star/Data'
with tifffile.TiffFile(src) as t:geo=t.geotiff_metadata
raw=tifffile.memmap(src);samples=np.array(raw[::2,::2],copy=True);valid=np.isfinite(samples)&(samples>-1e30);valid[[0,-1],:]=False;valid[:,[0,-1]]=False
height=np.zeros(samples.shape,dtype='<i2');height[valid]=np.rint(samples[valid].astype(np.float64)*4).astype(np.int16)
quant=float(np.max(abs(height[valid].astype(np.float64)*.25-samples[valid])));height.tofile(out/'apollo17_far_height_i16.bin')
distance=distance_transform_edt(valid);confidence=np.rint(np.minimum(distance/50,1)*255).astype(np.uint8);confidence[~valid]=0;confidence.tofile(out/'apollo17_far_confidence_u8.bin')
left,top=geo['ModelTiepoint'][3:5];left-=2.5;top+=2.5;sp=10.;h,w=samples.shape;rad=1737400.;scale=rad*np.cos(np.deg2rad(20));
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
meta=dict(schemaVersion=1,width=w,height=h,format='int16',endianness='little',layout='row-major',units='meters above1737400m sphere',heightScaleMeters=.25,binaryPath='Content/Star/Data/apollo17_far_height_i16.bin',confidencePath='Content/Star/Data/apollo17_far_confidence_u8.bin',pixelSpacingMeters=10,referenceRadiusMeters=rad,datumFrame='MOON_ME',longitudeConvention='planetocentric east-positive',projection='equirectangular',centralMeridianDegrees=180,standardParallelDegrees=20,topLeftPixelCornerProjectedMeters=[left,top],westLongitudeDegrees=180+np.rad2deg(left/scale),eastLongitudeDegrees=180+np.rad2deg((left+w*sp)/scale),northLatitudeDegrees=np.rad2deg(top/rad),southLatitudeDegrees=np.rad2deg((top-h*sp)/rad),sourceSampling='Original DTM pixel centers at source row2*j,col2*i; no height average, explicit 0.25m quantization.',sourcePostSpacingMeters=5,sourceShape=list(raw.shape),confidenceEncoding='0 invalid or source perimeter;1..255 valid, round(min(distanceToInvalidIn10mCells/50,1)*255). Runtime blend excludes first20m then smoothsteps to500m.',blendWidthMeters=500,blendInsetMeters=20,nearPreservation='Original5m file/interior unchanged;300m near edge blends to10m far, far mask edge toLOLA.',validFraction=float(valid.mean()),minHeightMeters=float(samples[valid].min()),maxHeightMeters=float(samples[valid].max()),maxQuantizationErrorMeters=quant,reportedPrecisionMeters=2.55,sourceUrl='https://pds.lroc.im-ldi.com/data/LRO-L-LROC-5-RDR-V1.0/LROLRC_2001/DATA/SDP/NAC_DTM/APOLLO17/NAC_DTM_APOLLO17.TIF',sourceSha256=sha(src),sourceObservationDate='2010-07-28..2016-03-17',credit='NASA/GSFC/Arizona State University; LROC team',residentBytes=int(height.nbytes+confidence.nbytes),artifacts=[dict(path=p.as_posix(),bytes=p.stat().st_size,sha256=sha(p)) for p in [out/'apollo17_far_height_i16.bin',out/'apollo17_far_confidence_u8.bin']]);(out/'apollo17_far.json').write_text(json.dumps(meta,indent=2)+'\n',encoding='utf-8',newline='\n');print(json.dumps({k:meta[k] for k in ['width','height','residentBytes','validFraction','maxQuantizationErrorMeters','minHeightMeters','maxHeightMeters']}),flush=True)
