"""Single-image estimated reflectance residual from unchanged georeferenced LROC mosaic."""
from pathlib import Path
import sys,json,hashlib,time,os
sys.path.insert(0,str(Path('work/lunar-panorama/python').resolve()))
import numpy as np,cv2,tifffile
from scipy.ndimage import gaussian_filter,minimum_filter,map_coordinates
from PIL import Image
ROOT=Path('.');src=Path('./work/trees/data/work/raw/NAC_DTM_APOLLO17_MOSAIC_5M.TIF');expected='8e3a2dff013059278a58daed87570cb963e37de46ef0639c95afd3a434fc92d7';digest=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();assert digest(src)==expected
print('PID',os.getpid(),'start',time.time(),flush=True)
meta=json.loads(Path('Content/Star/Data/apollo17_far.json').read_text());source=tifffile.memmap(src);valid=np.fromfile(meta['confidencePath'],dtype=np.uint8).reshape(meta['height'],meta['width']);out=Path('Content/Star/Art/LunarPanorama/OrbitalResidual');out.mkdir(exist_ok=True);cache=Path('work/lunar-panorama/orbital-residual');cache.mkdir(exist_ok=True);w=h=8192;dx=meta['width']*10/w;dy=meta['height']*10/h;halo=84
rgba=np.memmap(cache/'residual.u8',dtype=np.uint8,mode='w+',shape=(h,w,4));statistics=[]
def smooth(a,b,x):
 t=np.clip((x-a)/(b-a),0,1);return t*t*(3-2*t)
def extract(gray,hard,spacing):
 linear=np.where(gray<=.04045,gray/12.92,((gray+.055)/1.055)**2.4);log=np.log(np.maximum(linear,.003));weight=smooth(.10,.26,gray)*(1-smooth(.90,.99,gray))*hard
 sigma=(120/spacing[1],120/spacing[0]);den=gaussian_filter(weight,sigma,mode='nearest');num=gaussian_filter(log*weight,sigma,mode='nearest');low=np.divide(num,den,out=np.zeros_like(num),where=den>1e-6);residual=np.clip((log-low)*.28,-.32,.32)
 filtered=gaussian_filter(gray,(10/spacing[1],10/spacing[0]),mode='nearest');gy,gx=np.gradient(filtered);gradient=np.hypot(gx*5/spacing[0],gy*5/spacing[1]);confidence=weight*(1-smooth(.02,.07,gradient));confidence=gaussian_filter(confidence,(5/spacing[1],5/spacing[0]),mode='nearest');support=minimum_filter((hard&(gray>.10)&(gray<.99)).astype(np.uint8),size=3,mode='constant')>0;confidence*=support&(den>.20);residual=np.where(confidence>0,residual,0)
 return residual,confidence,support
for y0 in range(0,h,512):
 y1=min(y0+512,h);ya=max(0,y0-halo);yb=min(h,y1+halo);sx=(np.arange(w,dtype=np.float32)+.5)*(meta['width']*2/w)-1;sy=(np.arange(ya,yb,dtype=np.float32)+.5)*(meta['height']*2/h)-1;X,Y=np.meshgrid(sx,sy);gray=cv2.remap(source,X,Y,cv2.INTER_LINEAR,borderMode=cv2.BORDER_CONSTANT).astype(np.float32)/255
 nearest=cv2.remap(source,X,Y,cv2.INTER_NEAREST,borderMode=cv2.BORDER_CONSTANT);demvalid=map_coordinates(valid,[Y/2,X/2],order=0,mode='constant',cval=0)>0;hard=(nearest>0)&demvalid
 residual,confidence,support=extract(gray,hard,(dx,dy));crop=slice(y0-ya,y1-ya);residual=residual[crop];confidence=confidence[crop];support=support[crop]
 lon=np.deg2rad(meta['westLongitudeDegrees']+(np.arange(w)+.5)/w*(meta['eastLongitudeDegrees']-meta['westLongitudeDegrees']));lat=np.deg2rad(meta['northLatitudeDegrees']-(np.arange(y0,y1)+.5)/h*(meta['northLatitudeDegrees']-meta['southLatitudeDegrees']));L,P=np.meshgrid(lon,lat);lat0,lon0=np.deg2rad([20.1908,30.7717]);distance=1737400*np.arccos(np.clip(np.sin(lat0)*np.sin(P)+np.cos(lat0)*np.cos(P)*np.cos(L-lon0),-1,1));eligibility=support*smooth(1800,2200,distance)
 rgba[y0:y1,:,0]=np.rint(128+127*residual).astype(np.uint8);rgba[y0:y1,:,1]=np.rint(confidence.clip(0,1)*255).astype(np.uint8);rgba[y0:y1,:,2]=128;rgba[y0:y1,:,3]=np.rint(eligibility.clip(0,1)*255).astype(np.uint8)
 print('rows',y1,flush=True)
rgba.flush();path=out/'apollo17_orbital_residual_confidence_8192_linear.png';Image.fromarray(np.asarray(rgba)).save(path)
# Explicit controls: constant material must remain neutral; shadow/nodata must not gain support.
constant=np.full((256,256),.45,np.float32);one=np.ones((256,256),bool);cr,cg,_=extract(constant,one,(dx,dy));assert np.max(abs(cr[80:-80,80:-80]))<1e-5
control=constant.copy();control[80:120,80:120]=.03;cm=one.copy();cm[140:180,140:180]=False;nr,ng,_=extract(control,cm,(dx,dy));assert ng[85:115,85:115].max()==0 and ng[145:175,145:175].max()==0
# Image-coordinate window covering the east-facing source hills around17km from LM.
rad=1737400.;la,lo=np.deg2rad([20.1908,30.7717]);lon1=np.rad2deg(lo+17000/(rad*np.cos(la)));u=(lon1-meta['westLongitudeDegrees'])/(meta['eastLongitudeDegrees']-meta['westLongitudeDegrees']);v=(meta['northLatitudeDegrees']-20.1908)/(meta['northLatitudeDegrees']-meta['southLatitudeDegrees']);cx,cy=int(u*w),int(v*h);east=rgba[cy-450:cy+450,cx-650:cx+650];R=(east[:,:,0].astype(float)-128)/127;G=east[:,:,1]/255;A=east[:,:,3]/255;factor=1+R*G*A
info=dict(schemaVersion=1,status='LOCAL_ORBITAL_RESIDUAL_CANDIDATE_NOT_ALBEDO_MEASUREMENT',sourcePath=str(src),sourceUrl='https://pds.lroc.im-ldi.com/data/LRO-L-LROC-5-RDR-V1.0/LROLRC_2001/EXTRAS/BROWSE/NAC_DTM/APOLLO17/NAC_DTM_APOLLO17_MOSAIC_5M.TIF',sourceSha256=expected,sourceBytes=src.stat().st_size,sourcePixels=list(source.shape[::-1]),sourceObservationDate='2010-07-28..2016-03-17; mosaic product',sourceCredit='NASA/GSFC/Arizona State University; LROC team',sourcePixelSpacingMeters=5,datum='MOON_ME; planetocentric east-positive;1737400m sphere',texturePath=path.as_posix(),sha256=digest(path),pixels=[w,h],geographicBounds={k:meta[k] for k in ['westLongitudeDegrees','eastLongitudeDegrees','northLatitudeDegrees','southLatitudeDegrees']},metersPerTexelProjected=[dx,dy],channels=dict(R='signed residual encoded round(128+127*residual), residual clamped +/-0.32',G='0..1 photometric confidence',B='128 unused',A='source/DTM support and 1.8..2.2km distance fade'),shader='multiplier = 1 + ((R*255-128)/127)*G*A*strength; sRGB=false; base-color multiplier before ground-photo blend',nearExclusionMeters=1800,nearFullFadeMeters=2200,estimate='Assume display-coded mosaic, decode sRGB, confidence-weighted log high-pass sigma120m, gain0.28; NOT calibrated reflectance/albedo. Small baked shadow remains possible.',mask='Shadow DN<=25, saturation DN>=253, nodata, DTM invalid, high radiometric gradients, low baseline support;3px hard support erosion.',limits=['One mosaic cannot uniquely separate illumination and albedo.','5m source cannot recreate submeter rocks or change silhouette.','Photo panorama alpha and original mosaic untouched.','Root owns UE import/material/cook/game comparison.'],controls=dict(constantResidualMax=float(np.max(abs(cr[80:-80,80:-80]))),shadowConfidenceMax=float(ng[85:115,85:115].max()),nodataConfidenceMax=float(ng[145:175,145:175].max())),eastWindow=dict(pixelBox=[cx-650,cy-450,cx+650,cy+450],effectiveSupportFraction=float(np.mean(G*A>.1)),multiplierStandardDeviation=float(np.std(factor[G*A>.1])),multiplierPercentiles=np.quantile(factor[G*A>.1],[.01,.1,.5,.9,.99]).tolist()))
Path('Data/lunar_panorama_orbital_residual.json').write_text(json.dumps(info,indent=2)+'\n',encoding='utf-8',newline='\n');print(json.dumps(info),flush=True)
