from pathlib import Path
import json,hashlib,numpy as np
root=Path('.');meta=json.loads(Path('Content/Star/Data/apollo17_far.json').read_text());cpu=json.loads(Path('work/lunar-panorama/full-region/catalog_cpu.json').read_text());native=np.load('Content/Star/Art/LunarPanorama/FullRegion/dem_horizon_full.npz');runtime=np.genfromtxt('work/lunar-panorama/full-region/runtime_horizon.csv',delimiter=',',names=True);points=[]
for a in [0,20,225,240,255,295]:
 row=runtime[runtime['azimuth']==a][0];err=abs(float(row['elevation'])-float(native['elevation'][a*10]));assert err<.01;points.append(dict(azimuthDegrees=a,runtimeElevationDegrees=float(row['elevation']),nativeElevationDegrees=float(native['elevation'][a*10]),runtimePeakRangeMeters=float(row['distance']),nativePeakRangeMeters=float(native['distance'][a*10]),elevationErrorDegrees=err))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
old=json.loads(Path('Data/lunar_panorama_sources.json').read_text())['dtm'];assert sha(old['heightPath'])==old['heightSha256']
for a in meta['artifacts']:assert sha(a['path'])==a['sha256']
result=dict(schemaVersion=1,status='LOCAL_FAR_TIER_CPU_VALIDATED_NOT_UE_COMPILED',runtimeSampling=cpu,transition=json.loads(Path('work/lunar-panorama/full-region/transition_cpu.json').read_text()),nearHeightBinaryUnchanged=True,nearHeightSha256=old['heightSha256'],sourceNativeDtmSha256=meta['sourceSha256'],residentBytes=meta['residentBytes'],maxQuantizationErrorMeters=meta['maxQuantizationErrorMeters'],summitChecks=points,sourceFiles=[dict(path=p,sha256=sha(p)) for p in ['Source/Star/Runtime/StarDataCatalog.h','Source/Star/Runtime/StarDataCatalog.cpp']],limitations=['UE loader/compile/cook is root-owned and not executed here.','C++ shim compiles actual production sampling function bodies, not complete UE class.','Original5m interior preserved; existing300m edge now blends to10m far, then mask edge toLOLA.','Nodata edge falls back smoothly to coarse global LOLA; these blended elevations are not new observations.']);Path('Data/lunar_panorama_far_validation.json').write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8',newline='\n')
