"""Independently inspect the PCM container generated by the native DSP preview tool."""
from __future__ import annotations

import argparse
from array import array
from datetime import datetime, timezone
import hashlib
import json
import math
from pathlib import Path
import sys
import wave


def rms(samples: array, rate: int, start: float, end: float) -> float:
    values = samples[round(start * rate) * 2:round(end * rate) * 2]
    return math.sqrt(sum(int(x) ** 2 for x in values) / len(values)) / 32768.0


def main() -> None:
    root = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser()
    parser.add_argument("--directory", type=Path, default=root / "outputs/audio")
    args = parser.parse_args()
    wav_path = args.directory / "star-cockpit-audio-preview.wav"
    with wave.open(str(wav_path), "rb") as wav:
        assert (wav.getnchannels(), wav.getsampwidth(), wav.getframerate(), wav.getnframes()) == (2, 2, 48000, 1440000)
        assert wav.getcomptype() == "NONE"
        raw = wav.readframes(wav.getnframes())
    assert len(raw) == 5760000
    samples = array("h", raw)
    if sys.byteorder != "little":
        samples.byteswap()
    peak = max(abs(x) for x in samples) / 32768.0
    assert 0.02 < peak < 0.5, "Preview must contain signal with headroom."
    assert rms(samples, 48000, 24.04, 25.98) == 0.0, "Paused interval is not exactly silent."
    assert rms(samples, 48000, 28.04, 30.0) == 0.0, "Muted interval is not exactly silent."
    cabin_rms = rms(samples, 48000, 8.8, 9.8)
    exterior_rms = rms(samples, 48000, 11.0, 12.5)
    assert exterior_rms / cabin_rms < 0.035, "Exterior attenuation does not survive PCM conversion."
    # Adjacent samples of the same channel, including control-transition boundaries.
    maximum_step = max(abs(samples[i] - samples[i - 2]) for i in range(2, len(samples))) / 32768.0
    assert maximum_step < 0.05, "Preview has an unexpected discontinuity."
    source_files = [
        "Source/Star/Presentation/StarShipAudioDSP.h",
        "Source/Star/Presentation/StarShipAudioDSP.cpp",
        "Source/Star/Presentation/StarShipAudioComponent.h",
        "Source/Star/Presentation/StarShipAudioComponent.cpp",
        "Source/Star/Presentation/StarInstrumentWidget.h",
        "Source/Star/Presentation/StarInstrumentWidget.cpp",
        "Tests/Audio/ShipAudioDSPTests.cpp",
        "Tools/Audio/RenderAudioPreview.cpp",
    ]
    report = {
        "verified_utc": datetime.now(timezone.utc).isoformat(),
        "scope": "Independent PCM preview inspection; not Unreal, physical audio output or gameplay acceptance",
        "result": "PASS",
        "wav_sha256": hashlib.sha256(wav_path.read_bytes()).hexdigest(),
        "pcm_format": {"channels": 2, "bits": 16, "sample_rate_hz": 48000, "seconds": 30},
        "peak_dbfs": 20.0 * math.log10(peak),
        "exterior_to_cabin_db": 20.0 * math.log10(exterior_rms / cabin_rms),
        "maximum_adjacent_sample_step": maximum_step,
        "paused_and_muted_intervals_exact_silence": True,
        "current_source_sha256": {name: hashlib.sha256((root / name).read_bytes()).hexdigest() for name in source_files},
        "unreal_bridge_compile": "PENDING",
        "cockpit_render_and_game_audio_output": "PENDING",
    }
    (args.directory / "audio-preview-verification.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"PASS PCM header, duration, headroom, pause/mute silence, exterior attenuation ({report['exterior_to_cabin_db']:.2f} dB), transitions")


if __name__ == "__main__":
    main()
