#pragma once
#include "CoreMinimal.h"
#include "GameFramework/PlayerController.h"
#include "InputActionValue.h"
#include "StarViewTypes.h"
#include "GuidedTour/GuidedTour.h"
#include "Navigation/NavigationPilot.h"
#include "StarPlayerController.generated.h"

class UStarHUDWidget;
class UStarInputSettingsWidget;
class UStarExplorationSubsystem;
class UInputMappingContext;
class UInputAction;
class AStarShipPawn;
class AStarEVAPawn;
class UWidgetComponent;
class UWidgetInteractionComponent;
namespace star { struct FlightInput; namespace validation { class RoutePilot; } }

UCLASS()
class STAR_API AStarPlayerController : public APlayerController
{
    GENERATED_BODY()
public:
    AStarPlayerController();
    virtual void PlayerTick(float DeltaTime) override;
    // Call after external scenario restores and when entering/leaving the tour.
    // Permission is transient and never survives a restore or driver handoff.
    void ResetNavigation();
protected:
    virtual void BeginPlay() override;
    virtual void EndPlay(const EEndPlayReason::Type Reason) override;
    virtual void SetupInputComponent() override;
private:
    void UpdateVR();
    void RecenterVR();
    bool bVRRequested=false;
    UPROPERTY() TObjectPtr<UWidgetComponent> VRPanel;
    UPROPERTY() TObjectPtr<UWidgetInteractionComponent> VRPointer;
    void HandleAction(FName Action,float Value=1.0f);
    void SetWorldDateTime(const FString& Value);
    void InputStarted(const FInputActionValue& Value,FName Action);
    void InputCompleted(const FInputActionValue& Value,FName Action);
    void AxisChanged(const FInputActionValue& Value,FName Axis);
    void AxisCompleted(const FInputActionValue& Value,FName Axis);
    void ConfigureInput();
    void SetFlightPaused(bool Value);
    void SetMenuInputMode();
    void OpenInputSettings();
    void CloseInputSettings();
    void SelectTarget(const FString& BodyId);
    bool NavigationBypassed() const;
    void ConfirmNavigationTransfer();
    void ToggleNavigationAutopilot();
    void ToggleNavigationSafeBrake();
    void ApplyNavigationControls(star::FlightInput& Controls);
    void UpdateNavigationSnapshot();
    void ConfigureNavigationQA();
    void UpdateLocalFlightQABefore();
    void InjectLocalFlightQA(star::FlightInput& Controls);
    void UpdateLocalFlightQAAfter();
    bool bLocalFlightQA=false;
    bool bLocalFlightStressQA=false;
    star::FlightState LocalFlightQASaved;
    double LocalFlightQATravel=0;
    star::Vec3d LocalFlightQABeforeBodyPosition;
    bool CheckNavigationQADeadline();
    bool RequireNavigationQA(bool Condition,const TCHAR* Reason);
    void UpdateNavigationQABeforeFlight();
    void InjectNavigationQAInput(star::FlightInput& Controls);
    void ObserveNavigationQAControls(const star::FlightInput& Controls);
    void UpdateNavigationQAAfterFlight();
    void CaptureNavigationQAStage();
    void FinishNavigationQA(bool Success,const FString& Reason);
    void UpdateSnapshot(double Dt);
    bool SaveGame();
    bool LoadGame();
    void CapturePhoto();
    void SetStatus(const FString& Message,double Seconds=5.0);
    void UpdateBenchmark(double Dt);
    void UpdateSolarQA(double Dt);
    void UpdateVoyageMovie(double Dt);
    double VoyageRecordingStart=0;
    bool bVoyageAudioStopped=false;
    FDelegateHandle SolarScreenshotHandle;
    int32 SolarLastCapture=-1;
    void TickAstronomyQA();
    void UpdateUnifiedWorldQA(double Dt);
    bool UnifiedStartedNormally=false, UnifiedGuideChecked=false, UnifiedGuidePreserved=false;
    int32 UnifiedLastBucket=-1;
    uint8 UnifiedShots=0;
    double UnifiedPreviousClearance=0;
    double UnifiedNightHoldStarted=-1;
    star::Vec3d BenchmarkInitialEarthLocal;
    double BenchmarkInitialSunClearance=0;
    void ConfigureAcceptance();
    void UpdateAcceptanceBeforeFlight(star::FlightInput& Controls);
    void UpdateAcceptanceAfterFlight();
    void FinishAcceptance(bool Success,const FString& Reason);
    FString SaveFilename() const;
    void StartGuidedTour();
    void ManualTakeover();
    void UpdateGuidedTourCommand(double Dt);
    void ApplyGuidedTourControls(star::FlightInput& Controls) const;
    void UpdateGuidedTourObservation();
    void UpdateGuidedTourQA(double Dt);
    void SetEnhancedStarsEnabled(bool Enabled);
    void SetFlightAssistEnabled(bool Enabled);
    void ClearInputHandoff();
    void ToggleEVA();
    void TickEVA(double Dt);
    void TickEVAQA(double Dt);
    void RequestQAQuit();
    bool bQAQuitPending=false;
    bool bTourCameraHandoffChecked=false;
    bool bEVAQA=false;
    int32 EVAQAStage=0;
    double EVAQAElapsed=0;
    FString EVAQADirectory;
    FString EVAQAParkedFlight;
    star::Vec3d EVAQASavedFeet;
    FVector2D EVAQAMove=FVector2D::ZeroVector;
    UPROPERTY() TObjectPtr<AStarShipPawn> Ship;
    UPROPERTY() TObjectPtr<AStarEVAPawn> EVAPawn;
    double EVAFootstepDistance=0;
    bool bInteriorMonitor=true;
    UPROPERTY() TObjectPtr<UStarHUDWidget> HUD;
    UPROPERTY() TObjectPtr<UStarInputSettingsWidget> InputSettings;
    UPROPERTY() TObjectPtr<UStarExplorationSubsystem> Exploration;
    UPROPERTY() TObjectPtr<UInputMappingContext> FlightMappings;
    UPROPERTY() TArray<TObjectPtr<UInputAction>> Actions;
    FStarHUDSnapshot Snapshot;
    TMap<FName,float> Axes;
    bool bFlightPaused=true;
    bool bPhotoMode=false;
    bool bScanHeld=false;
    bool bBrakeHeld=false;
    bool bTakeoffRequested=false;
    bool bKeyboardLiftHeld=false;
    bool bNavigationInitialized=false;
    bool bNavigationSafetyPause=false;
    bool bNavigationBrakingRecovery=false;
    bool bNavigationQA=false;
    bool bNavigationQAPathReady=false;
    bool bNavigationQAStarted=false;
    bool bNavigationQAFinished=false;
    bool bNavigationQAStageAction=false;
    bool bNavigationQACapturePending=false;
    bool bNavigationQARecoveryBeforeGate=false;
    bool bNavigationQADeviceObserved=false;
    bool bNavigationQADeviceConnected=false;
    uint32 NavigationQADeviceGeneration=0;
    int32 NavigationQAStage=0;
    int32 NavigationQAAssertions=0;
    int32 NavigationQAFrames=0;
    double NavigationQAStartedWall=0;
    double NavigationQAStageWall=0;
    FString NavigationQADirectory;
    FString NavigationQAStageName;
    TArray<FString> NavigationQAEvents;
    TArray<FString> NavigationQAScreenshots;
    star::FlightState NavigationQAInitialFixture;
    star::FlightState NavigationQAHighSpeedFixture;
    star::FlightState NavigationQABeforeState;
    star::FlightState NavigationQABeforeAdvanceState;
    star::FlightInput NavigationQARequestedInput;
    star::FlightInput NavigationQAAppliedInput;
    double AutopilotManualThrottle=0;
    star::navigation::NavigationPilot Navigation;
    star::navigation::NavigationCommand NavigationCommand;
    bool bMainMenu=true;
    bool bSessionStarted=false;
    bool bOpenedInitialInputSettings=false;
    bool bBenchmark=false;
    bool bBenchmarkCaptureStarted=false;
    bool bBenchmarkShowUI=false;
    bool bAcceptance=false;
    bool bAcceptanceResume=false;
    bool bAcceptanceResumeLanded=false;
    bool bAcceptanceResumePhoto=false;
    bool bAcceptanceStarted=false;
    bool bAcceptanceFinished=false;
    bool bAcceptanceLandedSaved=false;
    bool bAcceptanceRouteComplete=false;
    bool bAcceptancePendingFailure=false;
    bool bGuidedTour=false;
    bool bGuidedTourFinished=false;
    bool bGuidedTourFailed=false;
    bool bGuidedTourActualScanComplete=false;
    bool bGuidedTourTest=false;
    bool bGuidedTourTestStarted=false;
    bool bGuidedTourQuitRequested=false;
    bool bVisualSettingsApplied=false;
    bool bEnhancedStars=false;
    bool bFlightAssistPreference=true;
    bool bGuidedTourAssistCaptured=false;
    bool bGuidedTourSavedFlightAssist=true;
    star::FlightInput GuidedTourControls;
    star::FlightMode GuidedTourMode=star::FlightMode::Maneuver;
    TUniquePtr<star::guided::GuidedTour> GuidedTourRuntime;
    FString GuidedTourPendingObjective;
    FString GuidedTourStage;
    FString GuidedTourTitle;
    FString GuidedTourFailure;
    FString GuidedTourQADirectory;
    double GuidedTourProgress=0;
    double GuidedTourQAElapsed=0;
    double GuidedTourQASampleElapsed=0;
    uint64 GuidedTourQASample=0;
    FString GuidedTourLastCaptureStage;
    double GuidedTourNextShotAt=-1;
    bool bGuidedTourRecording=false;
    bool bTourSaveSlot=false;
    bool bTourPreparing=false;
    double TourWarmSeconds=0;
    double TourResidentSeconds=0;
    TSharedPtr<star::validation::RoutePilot> AcceptancePilot;
    FString AcceptanceDirectory;
    FString AcceptanceStage;
    FString AcceptanceObjective;
    FString AcceptanceFailure;
    FString AcceptanceResumeBody;
    FString AcceptancePreviousFlight;
    double AcceptanceStartedAt=0;
    double AcceptanceLastSample=-1;
    double AcceptanceResumeSimulationTime=0;
    double AcceptanceResumeAltitude=0;
    uint64 AcceptanceInitialRecoveries=0;
    int32 BenchmarkStart=0;
    int32 BenchmarkCount=4;
    double BenchmarkStageSeconds=35;
    double BenchmarkShotSeconds=15;
    float BenchmarkThrottle=0;
    float BenchmarkLookYaw=0;
    float BenchmarkLookPitch=0;
    bool bBenchmarkPitchOverride=false;
    int32 BenchmarkStage=-1;
    double BenchmarkTime=0;
    double BenchmarkStageTime=0;
    FString BenchmarkPath;
    float KeyboardThrottle=0;
    float UIScale=1;
    float MasterVolume=0.5f;
    float LookSensitivity=1;
    float Exposure=0;
    double StatusExpires=0;
    double Clock=0;
    uint64 ObservationSequence=0;
    FString StatusMessage;
    FString LastPhotoRequest;
};
